language: python
python:
- '3.5'
- '3.6'
install:
- pip install django
script:
- python -c "__import__('sys').exit(0)"
deploy:
  provider: pypi
  user: isik-kaplan
  skip_existing: true
  password:
    secure: ZeUDd+haSiNWr0EpYdG+NsNZW/Bx6AtT1qwzcYB+tJgs8OSOzUyG5/cEb7vz1+4H+y49U6ddqD1ebSOpXmzZjU1tCaVEWjAcs3ogZRh102x1DOmzzQnkJa19jLIAu8X5x6j6PUb9NIk8Tq0DuPY4Q4Ln2QH0HzS6K3Ml+QL6ZJ4q3C2ksv1aiG3fqdPHLsgpNQ0GgXA2kQ90jd15AvK/lxrVPNZzT6MXtZloGS98aA1p1PJNOnAdlx8aN7SFtGmR9L3J0UbGkGP0nHTFCaBmIVyHz/AWfLSkHIZR/Q7WDGmHaDjoMb3EkGfmi+oxirLFiCsMUteCcUdmaYBVfszxNC+havPH/Ebq52yQ/hmAKAxJ4c0P5PVmx2MtzTZUXa1JXkKUDjcH/jK6rfQE6s4+J2uQB7seC8KkKnDIczwJq4ianPT3z09XL1vIo8hlncdcmB+8ERjmKRmXRZ+G/NEWFdPL3/aj6ag2nfe1nWY+W9g620WxkxjMFqCK/Yq9Yojzs7G9qTZwgxEzqVqU7fGG8bnAx18HmiyPDEmK9diSKp8vAm1C1s5aIKacSpRRQ3Lxc2qokh+NwSPmaiITvGl8tE/EZhr90oiFDPeOTkp9ib2rJkzU5O9iBQFTtI/dQEwYsvfKjyX6G1QVwGUS3Illp9PSl9d2OTM3di/gRNYZSkk=
