language: python
python:
- '3.5'
- '3.6'
install:
- pip install django
script:
- python -c "__import__('sys').exit(0)"
deploy:
  provider: pypi
  user: isik-kaplan
  skip_existing: true
  password:
    secure: WUry2TNxYoih5FqNsbKvK04XS4EwcNHeafRhkc0Wp0/PmVzj5wMTTKQ4hPveCijlqwECvqM6/mJHVPPX8KJr0ncft83zENWtGsxavTnPRyGftBXNblfFcVOwpp1mYJ4gTs0ddtCD7G3dRCtQAGbAkwng+Eut7UJe0DFi3OtfwrnPO0+x5scv2he4JfR+PXDF3yjhiTatHIu0yDazuFfn9PNhwLyheJRFQH51fNr6vP48hlFKymPTCC/e9c4f0624d3Mmelyp8P8OqjQxcitfT69dy040cVlKTfG/GWYfaulnbP9nwx2QaHSc1ip9hysQBJuVQQBLJ31QZmz2bEe4n0kNg7LSqgO3fcVi+SRaWktNofHrKcbJm0HgjjELyIMNV2WB8GagWx+rd/NqTs3Cz8lrjCIOkbgUyXyMmIQM0/s9klyIWcWBgPT7LFsLordP9+NYnqeJAjyhw7JtMBaFhTdkirHn4LAmVSMUezdIu3sBQ9PNq0wLu+PHtbNKIAzoYTwoCYrVIcd0aGHtB5GCGMcsGHn0m1R1j1QY5ZJF8X/GjElGk3yuS9GS8jjHsYId4fKksUi+YS/D0oOSlxPi66hEaMsHLH8Zwf18hHAHS5t6RFF9w+r9vItRHNhIrTVI4oErnjHzF/bnouqMmkWkzIlh4y6WGghqJRK1buYlUGQ=
