language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install django
deploy:
  provider: pypi
  user: isik-kaplan
  skip_existing: true
  password:
    secure: QfkZx9/u15cvI6aN4jDCEVSyVJyF8ieOCGWnUUlOoxWVdejkkEf7JJ8vb2Pw2xQNXyEXuJYow+UnxWe+3dndbO93rggjqwAY2iUYGPzgAnFHr72z8fiwNn4AR8HVcQx7cONtIVafkcIDuwyqBVbEfoMTyeq0H/vhYb1WdbQIklaa+9mWSgQL2nxQS70yUV5kEBfpDT09ZogY0UfwjS//io6aN8Xut0wa/Yx9n6ZmUQcwnYGem9l+NntlOdsigtzum9ZZImzJ3icNCfXCcNPO/m7fRgiJ0FwjH8yPNVOFX7xZeZwEwCgPvu7hpVCJ07gzLVFRD16o++ZY2gExZUL6M8hlwPemdwb7AlEySH3sGYdmCeA2yePSejx0VnwxC1nRsHQ7Du2B8iosV0zuBIPX8qcecyFR0ShV+o+2bAZKCngghuTJQTwqjXeNcKF3H9P64uvE+eTictpYcy61tNLL1UpItSbypZQsHnOcOggB1n8XC//43LPeAT6k4cocjW7PSZ9fAUt5E34nAW0XbG5mPbbkO8kDHNfaTXli9oof4zuhmLu+LarRoNvULtLNy7q8ONUEgv3y8S67GcFI37RUB+fCALRnMLVYi8tZ7dtO/dZrLPoEK4wTo7OuF+Alcuipe8xWw8IquzKkTHdNYWDXp5NdEv3dQ2Ybw/tm+beHYfY=

